### PR TITLE
chore: set imagePullPolicy for initContainer

### PR DESCRIPTION
**Pull request by fty4**
As already for the main container the case - the initContainer should also receive the `imagePullPolicy` value

https://github.com/eclipse-tractusx/daps-helm-chart/blob/5e25c56df1d66433f84217794fcc443a252e312a/charts/daps-server/templates/deployment.yaml#L98-L103

---
Marco Lecheler [marco.lecheler@mercedes-benz.com](mailto:marco.lecheler@mercedes-benz.com) Mercedes-Benz Tech Innovation GmbH ([ProviderInformation](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))

### CODE REVIEW

**Comment by carslen** [comment]
@wjost please ask someone from your team for a review of this PR, thanks!

**Comment by adkumar1** [comment]
You need to define it in deployment.yaml like this
imagePullPolicy: {{ .Values.init.image.pullPolicy }} 

And also you need to define a separate tag in values.yaml with respect to init image.
Something like this:

init:
  image:
    # -- Init container image
    repository: "alpine"
    # -- Image pull policy
    pullPolicy: Always
    # -- Image tag. Overrides the image tag whose default is the chart appVersion.
    tag: "3.17.3"
  # -- Pod security context configuration
  securityContext:
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

**Comment by fty4** [comment]
@adkumar1 This is related to PR #14 where I try to change the `initContainer` image (see: [PR14-diff](https://github.com/eclipse-tractusx/daps-helm-chart/pull/14/files#diff-6ce7c2a11e6d9f9f3f75c7c59ef6da96f3f2ed7930e33480c332eb8e5bb1695bR33)).
If this will be approved another key for the `initContainer` should not be required right?

It is more resource-efficient and easier to use the same image here instead of using another (small alpine) image.

**Comment by fty4** [comment]
_Note: 4a2542b - resolved merge conflict by merging `main` branch into PR branch `chore/initcontainer-imagepullpolicy`_

**Comment by adkumar1** [comment]
Change looks good

**Comment by wjost** [comment]
There are still merge conflicts on this branch.

**Comment by adkumar1** [comment]
@fty4 : Please fix conflicts

**Comment by fty4** [comment]
@adkumar1 / @wjost  merge conflict are solved

**Pull request merged**
